apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: An example deployment of a Backstage application.
  annotations:
    github.com/project-slug: backstage/demo
  tags:
    - recommended
    - laposte
    - webapi
spec:
  type: api
  lifecycle: experimental
